/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kunstmusik_jcsound_JCsound */

#ifndef _Included_com_kunstmusik_jcsound_JCsound
#define _Included_com_kunstmusik_jcsound_JCsound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kunstmusik_jcsound_JCsound
 * Method:    csoundCreate
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_kunstmusik_jcsound_JCsound_csoundCreate
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_kunstmusik_jcsound_JCsound
 * Method:    csoundReset
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_kunstmusik_jcsound_JCsound_csoundReset
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
